import { Product } from './types';

const brands = ["Nazm", "Shahi Adaayein", "Veerangana", "Suhaagan Saaj", "Noor-e-Nazakat", "Mehfil-e-Mohabbat"];

function getRandomBrand() {
  return brands[Math.floor(Math.random() * brands.length)];
}

export const mockProducts: Product[] = [
  {
    id: 'elegant-straight-suit',
    name: 'Elegant Straight Suit',
    description:
      'A beautifully crafted elegant straight suit, perfect for any occasion. Made with high-quality fabric and intricate embroidery.',
    price: '₹ 15,000',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/straight-suits/IMG_01.svg',
      '/straight-suits/IMG_02.svg',
      '/straight-suits/IMG_03.svg',
      '/straight-suits/IMG_04.svg',
    ],
    colors: [
      { name: 'Ivory', hex: '#F5F5DC' },
      { name: 'Black', hex: '#000000' },
      { name: 'Red', hex: '#FF0000' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    deliveryInfo:
      'We require 48 hours to dispatch the order & delivery will take 3-4 business days within India and 7-10 business days for International orders.',
    details: [
      { title: 'Product Details', content: 'Detailed information about the product.' },
      { title: 'Delivery & Returns', content: 'Information about delivery and return policies.' },
      { title: 'Disclaimer', content: 'Important disclaimers.' },
      { title: 'Customer Care', content: 'Contact information for customer support.' },
    ],
    category: 'straight-suits',
    imageUrl: '/straight-suits/IMG_01.svg',
    brand: getRandomBrand(),
  },
  {
    id: 'anarkali-suit',
    name: 'Anarkali Suit',
    description:
      'A stunning Anarkali suit with intricate designs, perfect for festive occasions.',
    price: '₹ 20,000',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/anarkali.jpg',
      '/anarkali.jpg',
      '/anarkali.jpg',
    ],
    colors: [
      { name: 'Blue', hex: '#0000FF' },
      { name: 'Green', hex: '#00FF00' },
    ],
    sizes: ['M', 'L'],
    deliveryInfo:
      'We require 48 hours to dispatch the order & delivery will take 3-4 business days within India and 7-10 business days for International orders.',
    details: [
      { title: 'Product Details', content: 'Detailed information about the Anarkali suit.' },
      { title: 'Delivery & Returns', content: 'Information about delivery and return policies.' },
      { title: 'Disclaimer', content: 'Important disclaimers.' },
      { title: 'Customer Care', content: 'Contact information for customer support.' },
    ],
    category: 'anarkali',
    imageUrl: '/anarkali.jpg',
    brand: getRandomBrand(),
  },
  {
    id: 'floral-straight-suit',
    name: 'Floral Straight Suit',
    description: 'A beautiful floral straight suit, perfect for casual wear.',
    price: '₹ 18,000',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/straight-suits/IMG_02.svg',
      '/straight-suits/IMG_01.svg',
      '/straight-suits/IMG_03.svg',
    ],
    colors: [
      { name: 'Ivory', hex: '#F5F5DC' },
      { name: 'Pink', hex: '#FFC0CB' },
    ],
    sizes: ['S', 'M', 'L'],
    deliveryInfo: 'Standard delivery: 3-5 business days.',
    details: [
      { title: 'Product Details', content: 'Made from breathable cotton fabric with elegant floral prints.' },
      { title: 'Delivery & Returns', content: 'Free returns within 30 days.' },
      { title: 'Disclaimer', content: 'Colors may vary slightly due to lighting.' },
      { title: 'Customer Care', content: 'Contact us at support@aakar.com.' },
    ],
    category: 'straight-suits',
    imageUrl: '/straight-suits/IMG_02.svg',
    brand: getRandomBrand(),
  },
  {
    id: 'embroidered-straight-suit',
    name: 'Embroidered Straight Suit',
    description: 'An elegant embroidered straight suit, ideal for festive occasions.',
    price: '₹ 22,000',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/straight-suits/IMG_03.svg',
      '/straight-suits/IMG_01.svg',
      '/straight-suits/IMG_02.svg',
    ],
    colors: [
      { name: 'Ivory', hex: '#F5F5DC' },
      { name: 'Gold', hex: '#FFD700' },
    ],
    sizes: ['M', 'L', 'XL'],
    deliveryInfo: 'Express delivery: 2-3 business days.',
    details: [
      { title: 'Product Details', content: 'Features intricate embroidery work on premium silk fabric.' },
      { title: 'Delivery & Returns', content: 'Exchange available within 15 days.' },
      { title: 'Disclaimer', content: 'Dry clean only.' },
      { title: 'Customer Care', content: 'Call us at +91 9876543210.' },
    ],
    category: 'straight-suits',
    imageUrl: '/straight-suits/IMG_03.svg',
    brand: getRandomBrand(),
  },
  {
    id: 'classic-straight-suit',
    name: 'Classic Straight Suit',
    description: 'A timeless classic straight suit, perfect for everyday elegance.',
    price: '₹ 16,500',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/straight-suits/IMG_04.svg',
      '/straight-suits/IMG_01.svg',
      '/straight-suits/IMG_02.svg',
    ],
    colors: [
      { name: 'Ivory', hex: '#F5F5DC' },
      { name: 'Grey', hex: '#808080' },
    ],
    sizes: ['S', 'M'],
    deliveryInfo: 'Standard delivery: 3-5 business days.',
    details: [
      { title: 'Product Details', content: 'Simple yet sophisticated design, made with comfortable fabric.' },
      { title: 'Delivery & Returns', content: 'Free returns within 30 days.' },
      { title: 'Disclaimer', content: 'Handle with care.' },
      { title: 'Customer Care', content: 'Visit our FAQ section for more.' },
    ],
    category: 'straight-suits',
    imageUrl: '/straight-suits/IMG_04.svg',
    brand: getRandomBrand(),
  },
  {
    id: 'modern-straight-suit',
    name: 'Modern Straight Suit',
    description: 'A contemporary modern straight suit, designed for the fashion-forward.',
    price: '₹ 19,500',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/straight-suits/IMG_05.svg',
      '/straight-suits/IMG_01.svg',
      '/straight-suits/IMG_02.svg',
    ],
    colors: [
      { name: 'Ivory', hex: '#F5F5DC' },
      { name: 'Navy', hex: '#000080' },
    ],
    sizes: ['L', 'XL'],
    deliveryInfo: 'Express delivery: 2-3 business days.',
    details: [
      { title: 'Product Details', content: 'Features a unique cut and modern patterns.' },
      { title: 'Delivery & Returns', content: 'Exchange available within 15 days.' },
      { title: 'Disclaimer', content: 'Limited stock available.' },
      { title: 'Customer Care', content: 'Email us for any queries.' },
    ],
    category: 'straight-suits',
    imageUrl: '/straight-suits/IMG_05.svg',
    brand: getRandomBrand(),
  },
  {
    id: 'party-wear-straight-suit',
    name: 'Party Wear Straight Suit',
    description: 'A dazzling party wear straight suit, perfect for special occasions.',
    price: '₹ 25,000',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/straight-suits/IMG_06.svg',
      '/straight-suits/IMG_01.svg',
      '/straight-suits/IMG_02.svg',
    ],
    colors: [
      { name: 'Ivory', hex: '#F5F5DC' },
      { name: 'Maroon', hex: '#800000' },
    ],
    sizes: ['M', 'L'],
    deliveryInfo: 'Standard delivery: 3-5 business days.',
    details: [
      { title: 'Product Details', content: 'Embellished with sequins and beads for a glamorous look.' },
      { title: 'Delivery & Returns', content: 'Free returns within 30 days.' },
      { title: 'Disclaimer', content: 'Hand wash only.' },
      { title: 'Customer Care', content: 'Reach out to us on social media.' },
    ],
    category: 'straight-suits',
    imageUrl: '/straight-suits/IMG_06.svg',
    brand: getRandomBrand(),
  },
  {
    id: 'casual-straight-suit',
    name: 'Casual Straight Suit',
    description: 'A comfortable casual straight suit, ideal for daily wear.',
    price: '₹ 14,000',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/straight-suits/IMG_07.svg',
      '/straight-suits/IMG_01.svg',
      '/straight-suits/IMG_02.svg',
    ],
    colors: [
      { name: 'Ivory', hex: '#F5F5DC' },
      { name: 'Beige', hex: '#F5F5DC' },
    ],
    sizes: ['S', 'M'],
    deliveryInfo: 'Standard delivery: 3-5 business days.',
    details: [
      { title: 'Product Details', content: 'Lightweight fabric for maximum comfort throughout the day.' },
      { title: 'Delivery & Returns', content: 'Exchange available within 15 days.' },
      { title: 'Disclaimer', content: 'Iron on low heat.' },
      { title: 'Customer Care', content: 'We are available 24/7.' },
    ],
    category: 'straight-suits',
    imageUrl: '/straight-suits/IMG_07.svg',
    brand: getRandomBrand(),
  },
  {
    id: 'designer-straight-suit',
    name: 'Designer Straight Suit',
    description: 'An exclusive designer straight suit, a statement piece.',
    price: '₹ 28,000',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/straight-suits/IMG_08.svg',
      '/straight-suits/IMG_01.svg',
      '/straight-suits/IMG_02.svg',
    ],
    colors: [
      { name: 'Ivory', hex: '#F5F5DC' },
      { name: 'Silver', hex: '#C0C0C0' },
    ],
    sizes: ['L', 'XL'],
    deliveryInfo: 'Express delivery: 2-3 business days.',
    details: [
      { title: 'Product Details', content: 'Unique design by renowned designers, limited edition.' },
      { title: 'Delivery & Returns', content: 'No returns on designer items.' },
      { title: 'Disclaimer', content: 'Handle with extreme care.' },
      { title: 'Customer Care', content: 'Personalized assistance available.' },
    ],
    category: 'straight-suits',
    imageUrl: '/straight-suits/IMG_08.svg',
    brand: getRandomBrand(),
  },
  {
    id: 'simple-straight-suit',
    name: 'Simple Straight Suit',
    description: 'A simple yet elegant straight suit, versatile for any occasion.',
    price: '₹ 13,500',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/straight-suits/IMG_09.svg',
      '/straight-suits/IMG_01.svg',
      '/straight-suits/IMG_02.svg',
    ],
    colors: [
      { name: 'Ivory', hex: '#F5F5DC' },
      { name: 'Brown', hex: '#A52A2A' },
    ],
    sizes: ['S', 'M'],
    deliveryInfo: 'Standard delivery: 3-5 business days.',
    details: [
      { title: 'Product Details', content: 'Minimalist design, easy to style for various looks.' },
      { title: 'Delivery & Returns', content: 'Free returns within 30 days.' },
      { title: 'Disclaimer', content: 'Machine wash cold.' },
      { title: 'Customer Care', content: 'Chat with us online.' },
    ],
    category: 'straight-suits',
    imageUrl: '/straight-suits/IMG_09.svg',
    brand: getRandomBrand(),
  },
  {
    id: 'anarkali-gown',
    name: 'Anarkali Gown',
    description: 'A grand Anarkali gown, perfect for weddings and grand events.',
    price: '₹ 30,000',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/anarkali.jpg',
      '/anarkali.jpg',
      '/anarkali.jpg',
    ],
    colors: [
      { name: 'Blue', hex: '#0000FF' },
      { name: 'Gold', hex: '#FFD700' },
    ],
    sizes: ['M', 'L'],
    deliveryInfo: 'Express delivery: 2-3 business days.',
    details: [
      { title: 'Product Details', content: 'Flowing silhouette with rich embellishments.' },
      { title: 'Delivery & Returns', content: 'Exchange available within 15 days.' },
      { title: 'Disclaimer', content: 'Dry clean only.' },
      { title: 'Customer Care', content: 'Contact us for custom sizing.' },
    ],
    category: 'anarkalis',
    imageUrl: '/anarkali.jpg',
    brand: getRandomBrand(),
  },
  {
    id: 'anarkali-dress',
    name: 'Anarkali Dress',
    description: 'A beautiful Anarkali dress, suitable for semi-formal gatherings.',
    price: '₹ 27,000',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/anarkali.jpg',
      '/anarkali.jpg',
      '/anarkali.jpg',
    ],
    colors: [
      { name: 'Green', hex: '#00FF00' },
      { name: 'Silver', hex: '#C0C0C0' },
    ],
    sizes: ['S', 'M'],
    deliveryInfo: 'Standard delivery: 3-5 business days.',
    details: [
      { title: 'Product Details', content: 'Comfortable fit with elegant design.' },
      { title: 'Delivery & Returns', content: 'Free returns within 30 days.' },
      { title: 'Disclaimer', content: 'Colors may vary slightly.' },
      { title: 'Customer Care', content: 'We are here to help.' },
    ],
    category: 'anarkalis',
    imageUrl: '/anarkali.jpg',
    brand: getRandomBrand(),
  },
  {
    id: 'anarkali-frock',
    name: 'Anarkali Frock',
    description: 'A stylish Anarkali frock, perfect for a chic look.',
    price: '₹ 29,000',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/anarkali.jpg',
      '/anarkali.jpg',
      '/anarkali.jpg',
    ],
    colors: [
      { name: 'Red', hex: '#FF0000' },
      { name: 'Black', hex: '#000000' },
    ],
    sizes: ['L', 'XL'],
    deliveryInfo: 'Express delivery: 2-3 business days.',
    details: [
      { title: 'Product Details', content: 'Modern cut with traditional elements.' },
      { title: 'Delivery & Returns', content: 'Exchange available within 15 days.' },
      { title: 'Disclaimer', content: 'Dry clean recommended.' },
      { title: 'Customer Care', content: 'Reach out for any assistance.' },
    ],
    category: 'anarkalis',
    imageUrl: '/anarkali.jpg',
    brand: getRandomBrand(),
  },
  {
    id: 'amra-embroidery-anarkali',
    name: 'Amra Embroidery - Anarkali',
    description: 'A beautifully embroidered Anarkali suit with intricate details.',
    price: '₹ 27,500',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/dress3.png',
      '/dress3.png',
      '/dress3.png',
    ],
    colors: [
      { name: 'Mint Green', hex: '#98FF98' },
    ],
    sizes: ['S', 'M', 'L'],
    deliveryInfo: 'Standard delivery: 3-5 business days.',
    details: [
      { title: 'Product Details', content: 'Detailed information about the product.' },
      { title: 'Delivery & Returns', content: 'Information about delivery and return policies.' },
      { title: 'Disclaimer', content: 'Important disclaimers.' },
      { title: 'Customer Care', content: 'Contact information for customer support.' },
    ],
    category: 'anarkalis',
    imageUrl: '/dress3.png',
    brand: getRandomBrand(),
  },
  {
    id: 'tissue-silk-anarkali',
    name: 'Tissue Silk - Anarkali',
    description: 'An elegant Tissue Silk Anarkali suit, perfect for special occasions.',
    price: '₹ 23,500',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/dress2.png',
      '/dress2.png',
      '/dress2.png',
    ],
    colors: [
      { name: 'Ivory', hex: '#FFFFF0' },
    ],
    sizes: ['M', 'L', 'XL'],
    deliveryInfo: 'Standard delivery: 3-5 business days.',
    details: [
      { title: 'Product Details', content: 'Detailed information about the product.' },
      { title: 'Delivery & Returns', content: 'Information about delivery and return policies.' },
      { title: 'Disclaimer', content: 'Important disclaimers.' },
      { title: 'Customer Care', content: 'Contact information for customer support.' },
    ],
    category: 'anarkalis',
    imageUrl: '/dress2.png',
    brand: getRandomBrand(),

  },
  {
    id: 'chinon-crape-anarkali',
    name: 'Chinon Crape - Anarkali',
    description: 'A luxurious Chinon Crape Anarkali suit, exuding royalty.',
    price: '₹ 43,500',
    mrpText: 'MRP inclusive of all taxes',
    images: [
      '/dress.png',
      '/dress.png',
      '/dress.png',
    ],
    colors: [
      { name: 'Peach', hex: '#FFDAB9' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    deliveryInfo: 'Standard delivery: 3-5 business days.',
    details: [
      { title: 'Product Details', content: 'Detailed information about the product.' },
      { title: 'Delivery & Returns', content: 'Information about delivery and return policies.' },
      { title: 'Disclaimer', content: 'Important disclaimers.' },
      { title: 'Customer Care', content: 'Contact information for customer support.' },
    ],
    category: 'anarkalis',
    imageUrl: '/dress.png',
    brand: getRandomBrand(),
  },
];